// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAy1Visny12D6LM1LAnAYNUNmLTWzWB_t8',
    appId: '1:640076845828:web:a360a7698b8363b7697651',
    messagingSenderId: '640076845828',
    projectId: 'try218122025ecomappprj',
    authDomain: 'try218122025ecomappprj.firebaseapp.com',
    storageBucket: 'try218122025ecomappprj.firebasestorage.app',
    measurementId: 'G-FV37QNRPMH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByrFzR04bW72BXpA_cYvXw25vnLg12Yuo',
    appId: '1:640076845828:android:872d7b4246d97ca6697651',
    messagingSenderId: '640076845828',
    projectId: 'try218122025ecomappprj',
    storageBucket: 'try218122025ecomappprj.firebasestorage.app',
  );

}